### ISSUE TITLE
Homework 02 link creates file, but page is blank

### ISSUE THREAD

**Issue by conradzesty** [ccsf-math-108/materials-sp24#4]
I need a bit of assistance
When I try to open the Homework 02 link from the homework module, it looks like a [file](https://ccsf.cloudbank.2i2c.cloud/user/calano1@mail.ccsf.edu/notebooks/materials-sp24/hw/hw02/hw02.ipynb) is created, but the page is blank. 
Please advise. Thank you.

**Comment by shawnwiggins** [comment]
Hi @conradzesty. Thanks for posting an issue. I can see that other students can access Homework 02 and have submitted it, so this might be something to message your instructor directly about. (I can't tell by your username if you are my student or @amclanahan's.) I'll close this issue here since this doesn't seem to be impacting everyone.
